// @flow
import { type Theme } from '../config/theme';

export default (theme: Theme) => ({
  component: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    padding: [[20, 0]],
    width: 150,
    position: 'relative',
    '&:hover $hoverIconWrapper': {
      display: 'flex',
    },
    textDecoration: 'none',
  },
  icon: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 5,
  },
  ext: {
    position: 'absolute',
    fontFamily: theme.typography.font.family2,
    fontSize: 10,
    color: theme.palette.primary.color2,
    fontWeight: '500',
    textTransform: 'uppercase',
  },
  iconImage: {
    width: 50,
    height: 50,
  },
  filename: {
    fontFamily: theme.typography.font.family2,
    fontSize: 13,
    color: theme.palette.blueGrey['50'],
  },
  hoverIconWrapper: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.3)',
    display: 'none',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
  },
  linkIconWrapper: {
    padding: 5,
    borderRadius: '50%',
    border: '2px solid white',
    width: 20,
    height: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 5,
  },
  linkIcon: {
    fontSize: '20px !important',
    color: 'white',
    cursor: 'pointer',
  },
  closeIconWrapper: {
    padding: 5,
    borderRadius: '50%',
    border: '2px solid white',
    width: 20,
    height: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeIcon: {
    color: 'white',
    fontSize: '20px !important',
    cursor: 'pointer',
  },
});
