const height = 204;
const width = 250;
export default theme => ({
  component: {
    height: height,
    width,
    display: 'flex',
  },
  root: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  upperPart: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '30px 20px',
    border: '2px solid',
    borderColor: props => props.borderColor || theme.palette.primary.color1,
    borderTopRightRadius: 5,
    borderTopLeftRadius: 5,
  },
  letterImage: {
    width: 50,
    height: 50,
    minHeight: 50,
    borderRadius: '50%',
    backgroundColor: props => props.borderColor || theme.palette.primary.color1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 18,
    fontFamily: theme.typography.font.family2,
    fontWeight: 500,
    color: 'white',
    marginBottom: 20,
  },
  cardImage: {
    width: 50,
    height: 50,
    marginBottom: 20,
    '& img': {
      width: '100%',
      height: '100%',
      borderRadius: '50%',
    },
  },
  primaryLabel: {
    fontSize: 18,
    fontFamily: theme.typography.font.family2,
    fontWeight: 500,
    color: theme.palette.primary.color3,
  },
  lowerPart: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0px 20px',
    border: '2px solid',
    borderColor: props => props.borderColor || theme.palette.primary.color1,
    borderTop: '0px solid',
    borderBottomRightRadius: 5,
    borderBottomLeftRadius: 5,
    height: 53,
  },
  secondaryLabel: {
    fontSize: 16,
    fontFamily: theme.typography.font.family2,
    color: theme.palette.primary.color3,
  },
  settingIcon: {
    fontSize: 25,
    color: '#2AC88F',
    cursor: 'pointer',
  },
});
