import React, { Component } from 'react';
import { theming } from 'components/config/theme';
import cx from 'classnames';
import _ from 'lodash';
import PropTypes from 'prop-types';
import injectSheet from 'react-jss';

export default styles => component => {
  const StyledComponent = injectSheet(styles, { theming })(component);
  class Wrapper extends Component {
    static propTypes = {
      classes: PropTypes.object,
    };

    state = {
      classes: {},
    };

    _mergeClasses = props => {
      // Merge classes generated by JSS and user classes
      let oldClasses = this.styledComponent.state.classes;
      let userClasses = props.classes || {};
      Object.keys(oldClasses).forEach(classKey => {
        oldClasses[classKey] = cx(oldClasses[classKey], userClasses[classKey]);
      });
      this.setState({ classes: oldClasses });
    };

    componentDidMount() {
      this._mergeClasses(this.props);
    }

    componentDidUpdate(prevProps) {
      if (!_.isEqual(this.props.classes, prevProps.classes)) {
        this._mergeClasses(this.props);
      }
    }

    render() {
      let { classes, ...rest } = this.props; // eslint-disable-line
      return (
        <StyledComponent
          ref={ref => {
            this.styledComponent = ref;
          }}
          {...rest}
          classes={this.state.classes}
        />
      );
    }
  }
  Wrapper.displayName = StyledComponent.displayName;
  return Wrapper;
};

export const composeStyles = (...styles) => (theme: Theme) => {
  let mergedStyles = {};
  styles.forEach((v, i) => {
    const style = v(theme);
    mergedStyles = {
      ...mergedStyles,
      ...style,
    };
  });
  return mergedStyles;
};
